GET http://{your_URL}/students

###
GET http://{your_URL}/students/2

###
POST http://{your_URL}/students
Content-Type: application/json

{
    "name": "another TEST",
    "categoryId": 2,
    "age": 14
}

###
PUT http://{your_URL}/students/2
Content-Type: application/json

{
    "name": "John",
    "categoryId": 3,
    "age": 18
}

###
DELETE http://{your_URL}/students/3