GET http://{your_URL}/teachers

###
GET http://{your_URL}/teachers/1

###
POST http://{your_URL}/teachers
Content-Type: application/json

{
    "name": "TEST",
    "age": 49,
    "categoryId": 2
}

###
PUT http://{your_URL}/teachers/1
Content-Type: application/json

{
    "name": "Jesse",
    "age": 32,
    "categoryId": 2
}

###
DELETE http://{your_URL}/teachers/3
